### PR TITLE
Sync methods

### PR DESCRIPTION
**Pull request by creynders**
See #7 @JohnnyEstilles think this suffices?
If so, I merge it in and cut a new release

### CODE REVIEW

**Comment by creynders** [comment]
Straight from the docs:

#### Adding hooks to synchronized methods

`addSyncHooks` allows you to register methods for enforced synchronized middleware execution (`addHooks` allows mixing of both and will _always_ finish async):

``` js
var grappling = require('grappling-hook');

var instance = {
    saveSync : function(filename){
        filename = Date.now() + "-" + filename; 
        console.log('save', filename);
        return filename;
    }
};

grappling.mixin(instance); // add grappling-hook functionality to an existing object

instance.addSyncHooks('saveSync'); // setup hooking for an existing (sync) method

instance.pre('saveSync', function(){
    console.log('saving!');
}).post('saveSync', function(){
    console.log('saved!');
});

var newName = instance.saveSync("example.txt");
console.log('new name:', newName);
```

``` sh
# output:
saving!
save 1431264587725-example.txt
saved!
new name: 1431264587725-example.txt
```

Middleware registered with synchronized hook will **NOT** receive `next` nor `done` callbacks, i.e. async serial or parallel middleware registration is not possible.

**Comment by creynders** [comment]
### Synchronized hooks

I you want to enforce a synchronized execution of hook middleware you can use `callSyncHook`.

``` js
instance.pre('saveSync', function syncMiddleware(foo, bar){
    console.log("middleware", foo, bar);
});

console.log('before callSyncHook');
instance.callSyncHook('pre:saveSync', 'foo', 'bar');
console.log('after callSyncHook');
```

```
# output:
before callSyncHook
middleware foo bar
after callSyncHook
```

`callSyncHook` does **NOT** provide `next` nor `done` callbacks to the middleware, neither does it allow passing a "final" callback to the method itself.

**Comment by estilles** [comment]
Just tested this. This is exactly what I was proposing. It works great in my use-cases! Can't wait to see it merged.

**Comment by creynders** [comment]
Landed in `v2.4.0`

**Pull request closed without merging**
